### ISSUE TITLE
Error while starting Kafka (Cannot start Schema Registry, Kafka Server is not running. Check your deployment)

### ISSUE THREAD

**Issue by viveksinghggits** [confluentinc/confluent-cli#120]
so, I followed this guide to get the Kafka running 

https://docs.confluent.io/current/quickstart/ce-quickstart.html#ce-quickstart

and it worked perfectly fine for sometime.
I recently started getting this error while starting the services 
```
This CLI is intended for development only, not for production
https://docs.confluent.io/current/cli/index.html

Using CONFLUENT_CURRENT: /tmp/confluent.llaA9yuK
Starting zookeeper
zookeeper is [UP]
Starting kafka
-Kafka failed to start
kafka is [DOWN]
Cannot start Schema Registry, Kafka Server is not running. Check your deployment

```
I looked into some previously raised issues but that was not very helpful. Anyone has any idea on how to debug this, or its better to have the complete log displayed here.

I am running ```Confluent Platform: 5.1.0``` on 
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"

```
machine.

**Comment by DaveSlinn** [comment]
Is this still a problem?  If so, can you post the results of running 

``confluent log kafka``

This should give more detail about why kafka failed to start.

**Comment by viveksinghggits** [comment]
@DaveSlinn I used another image to run Kafka, this wasnt working for me.

**Comment by Ptn006** [comment]
@DaveSlinn when I tried to run 'confluent log kafka', getting error as:
/tmp/confluent.wVjsxCdB/kafka/kafka.stdout: No such file or directory

**Comment by robertjin** [comment]
I got the same issue when I first setup and updating the following fixed it for me:

In /etc/kafka/server.properties, comment out the broker.id=0 line and add the following line to enable broker id generation

#broker.id=0
broker.id.generation.enable=true

**Comment by tianhao-au** [comment]
I am having the same issue with Confluent 5.2.1

**Comment by viveksinghggits** [comment]
I am not using this right now, so maintainer can close the issue.

**Comment by CIoann** [comment]
Basically you should: 
sudo rm -fr /tmp/confl*
confluent start

**Comment by ramdhakne** [comment]
What worked for me is running `jps` and then killing all pids. 

```
$ jps
94165 Jps
52807 KsqlServerMain
52521 KafkaRestMain
52394 SchemaRegistryMain
53386 Ksql
52922 ControlCenter
52253 SupportedKafka
52607 ConnectDistributed

$ kill -9 52807 52521 52394 53386 52922 52253 52607
```

```
$ confluent local stop
```

and then

```
confluent local start
```

**Comment by stychu** [comment]
@ramdhakne thanks this helped!

**Comment by toanmxpixta** [comment]
@ramdhakne Thank you

**Comment by ChaosOrb781** [comment]
Had the same problem, in my experience, you do not have to manually kill each process as the confluent command "confluent local destroy" will kill each of its running processes allowing new ones to spawn, try that before attempting to kill processes manually

**Comment by mzoz** [comment]
so frustrated, the setting up is ridiculously hassling, errors popping out in almost every step

**Comment by cfitchVFC** [comment]
So I am trying to get 5.4 going to no avail - Sometimes it looks like everything is up and then I immediately do a status and stuff is down - anyone running into this? typically control-center will no t come up and fails on start but sometimes it LOOKS like it does but again doing a status a bunch of stuff is down

**Comment by syntaxerr** [comment]
Yeah, I am using latest download 5.4 and get the following error.  

**Cannot start Schema Registry, Kafka Server is not running. Check your deployment
Error: exit status 127**


 The local commands are intended for a single-node development environment
    only, NOT for production usage. https://docs.confluent.io/current/cli/index.html

Using CONFLUENT_CURRENT: /tmp/confluent.GZnmCfjj
Starting zookeeper
zookeeper is [UP]
Starting kafka
|Kafka failed to start
kafka is [DOWN]
Cannot start Schema Registry, Kafka Server is not running. Check your deployment
Error: exit status 127

**Comment by vpahal3** [comment]
Using confluent version : 5.4.1
Step 1: Check for error log using below command : 
               confluent local log kafka f
For me it was port 8090 already in use
Step 2: Check port already in use command
                  netstat -vanp tcp | grep 8090
                                or
                  sudo lsof -i tcp:8090
Step 3: Update etc/config/server.properties file
                Uncomment and update the port in below line as below:
                    a) line 193 => confluent.metadata.server.listeners=http://0.0.0.0:8095
                    b) line 195 => confluent.metadata.server.advertised.listeners=http://127.0.0.1:8095
Step 4: Clean previous run : confluent local destroy

**Comment by mwws** [comment]
> Basically you should:
> sudo rm -fr /tmp/confl*
> confluent start

It helps, thanks a lot

**Comment by suvadipg** [comment]
trying to setup on Ubuntu image on Windows and getting flowing error while setting up confluent-5.5.0-2.12

Using CONFLUENT_CURRENT: /tmp/confluent.UWGFhyBm
Starting zookeeper
zookeeper is [UP]
Starting kafka
|Kafka failed to start
kafka is [DOWN]
Cannot start Schema Registry, Kafka Server is not running. Check your deployment
Error: exit status 127

**Comment by kala28** [comment]
> trying to setup on Ubuntu image on Windows and getting flowing error while setting up confluent-5.5.0-2.12
> 
> Using CONFLUENT_CURRENT: /tmp/confluent.UWGFhyBm
> Starting zookeeper
> zookeeper is [UP]
> Starting kafka
> |Kafka failed to start
> kafka is [DOWN]
> Cannot start Schema Registry, Kafka Server is not running. Check your deployment
> Error: exit status 1

> trying to setup on Ubuntu image on Windows and getting flowing error while setting up confluent-5.5.0-2.12
> 
> Using CONFLUENT_CURRENT: /tmp/confluent.UWGFhyBm
> Starting zookeeper
> zookeeper is [UP]
> Starting kafka
> |Kafka failed to start
> kafka is [DOWN]
> Cannot start Schema Registry, Kafka Server is not running. Check your deployment
> Error: exit status 127

1. Check your confluent status:
 code: confluent local status.
(all must be down, if its not then stop the confluent code- confluent local stop)
2. now copy paste this code below.
sudo rm -fr /tmp/confl*
3. Start your confluent.
confluent local start.

**Comment by NLe1** [comment]
jps and kill -9 all of the process worked for me! Thanks @ramdhakne

**Comment by akram-devtools** [comment]
jps and kill -9 all of the process worked for me as well. Thanks @ramdhakne

**Comment by samanmunikar** [comment]
Basically, I ran 
`confluent log kafka`
command and read the logs. I found out that port 9092 was already occupied so I freed the port using
`fuser -k 9092/tcp `
command.

**Comment by abomb302** [comment]
> running `jps` and then killing all pids.

this worked for me

**Comment by Kiran-G1** [comment]
This is a port problem.
If you see any of the services are down like this
`Starting zookeeper
zookeeper is [UP]
Starting kafka
kafka is [UP]
Starting schema-registry
schema-registry is [UP]
Cannot start Kafka Rest, Kafka Server is not running. Check your deployment
`
then check the log of kafka using command
`./confluent log kafka`
scroll and check for any port errors like below

`kafka.common.KafkaException: Socket server failed to bind to 0.0.0.0:9092: Address already in use.
        at kafka.network.Acceptor.openServerSocket(SocketServer.scala:441)
        at kafka.network.Acceptor.<init>(SocketServer.scala:331)
        at kafka.network.SocketServer$$anonfun$createAcceptorAndProcessors$1.apply(SocketServer.scala:148)
        at kafka.network.SocketServer$$anonfun$createAcceptorAndProcessors$1.apply(SocketServer.scala:144)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
`
if you find any port that is already being used some other process then find that process using the below command
`sudo lsof -i :9092`
then kill all those process ids using below command
`sudo kill -9 process_id`

**Comment by ilayatshah** [comment]
I am unable to start the Confluent as it gives me the following error
Using CONFLUENT_CURRENT: /tmp/confluent.040021
Starting ZooKeeper
ZooKeeper is [UP]
Starting Kafka
Kafka is [UP]
Starting Schema Registry
Error: Schema Registry failed to start

**Comment by SrinivasMurthyMutnurugithub** [comment]
> Basically you should: sudo rm -fr /tmp/confl* confluent start

Thanks it worked
